version: "3"

services:
    pact-broker:
        image: "pactfoundation/pact-broker:latest"
        ports:
            - "9292:9292"
        environment:
            PACT_BROKER_PORT: "9292"
            PACT_BROKER_DATABASE_URL: "postgres://postgres:avesta@192.168.168.68:5432/pact-flow"
            PACT_BROKER_LOG_LEVEL: INFO
            PACT_BROKER_SQL_LOG_LEVEL: DEBUG
            PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES: "5"
            PACT_BROKER_BASE_URL: "http://localhost:9292"
            PACT_BROKER_WEBHOOK_SCHEME_WHITELIST: "http"
            PACT_BROKER_WEBHOOK_HOST_WHITELIST: chat.shreeapp.com
